title: Herm's Blog
description: 
author: Herm
logo: /static/img/avatar.jpg
github: https://github.com/zhqherm
about: Share ideas.
keyword: "herm, blog, software engineer" 

baseurl: ""
url: "https://zhqherm.github.io/"

allowsearch: true

# disqus_shortname: aboutherm
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000

# SNS settings
github_username: Herm

enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
