# Permalinks
permalink:           pretty

# Setup
title:               Progress
tagline:             A responsive blog theme that illustrates reading progress. Suited for continous reading.
url:                 https://zhqherm.github.io/
baseurl:             /progress-for-jekyll
analytics_id:

# Owner/author information
owner:
  name:           Herm
  avatar:         avatar.png
  bio:            "Designer."
  email:          zhq204@qq.com
  twitter:        alexanderussell
  github:         zhqherm
  location:       "GZ, China"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
